default: &default
  adapter: postgresql
  user: postgres
  password:
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: seccomp-dev

test:
  <<: *default
  database: seccomp-test

production:
  <<: *default
  database: seccomp-production
